import type { DrugInfo } from '../pkpd/types';

export const ESTROGENS: Record<string, DrugInfo> = {
  E2_oral: {
    name: 'Estradiol Oral',
    therapeutic: [50, 200],
    unit: 'pg/mL',
    CL: 60,
    Vd: 60,
    ka: 0.04,
    F: 0.03,
    halfLife: 1,
    halfLifeApparent: 17,
    doseUnit: 'mg',
    intervalUnit: 'h',
    defaultDose: 2,
    defaultInterval: 12,
    ref: 'PMID: 1548642 | PMC7878477'
  },
  E2V_oral: {
    name: 'Estradiol Valerate Oral',
    therapeutic: [50, 200],
    unit: 'pg/mL',
    CL: 60,
    Vd: 60,
    ka: 0.04,
    F: 0.03,
    halfLife: 1,
    halfLifeApparent: 17,
    doseUnit: 'mg',
    intervalUnit: 'h',
    defaultDose: 2,
    defaultInterval: 12,
    ref: 'PMID: 1548642 | PMID 9793623'
  },
  E2_subl: {
    name: 'Estradiol Sublingual',
    therapeutic: [50, 200],
    unit: 'pg/mL',
    CL: 15,
    Vd: 150,
    ka: 2.5,
    F: 0.10,
    halfLife: 12,
    doseUnit: 'mg',
    intervalUnit: 'h',
    defaultDose: 2,
    defaultInterval: 12,
    ref: 'PMID: 9052581'
  },
  E2_td: {
    name: 'Estradiol Transdermal Patch',
    therapeutic: [50, 200],
    unit: 'pg/mL',
    CL: 10,
    Vd: 150,
    ka: 0.03,
    F: 0.85,
    halfLife: 36,
    doseUnit: 'mg',
    intervalUnit: 'h',
    defaultDose: 0.05,
    defaultInterval: 84,
    ref: 'PMID: 9689205'
  },
  E2_td_gel: {
    name: 'Estradiol Transdermal Gel',
    therapeutic: [10, 50],
    unit: 'pg/mL',
    CL: 10,
    Vd: 120,
    ka: 0.05,
    F: 0.90,
    halfLife: 30,
    doseUnit: 'μg',
    intervalUnit: 'h',
    defaultDose: 0.72,
    defaultInterval: 24,
    ref: 'Clinical pharmacokinetics'
  },
  E2V: {
    name: 'Estradiol Valerate IM',
    therapeutic: [100, 400],
    unit: 'pg/mL',
    CL: 100,
    Vd: 2400,
    ka: 0.012,
    F: 0.85,
    halfLife: 120,
    doseUnit: 'mg',
    intervalUnit: 'h',
    defaultDose: 5,
    defaultInterval: 168,
    ref: 'TfS Meta-analysis | PMID: 7169965'
  },
  E2C: {
    name: 'Estradiol Cypionate IM',
    therapeutic: [100, 400],
    unit: 'pg/mL',
    CL: 120,
    Vd: 2800,
    ka: 0.006,
    F: 0.90,
    halfLife: 192,
    doseUnit: 'mg',
    intervalUnit: 'h',
    defaultDose: 5,
    defaultInterval: 168,
    ref: 'TfS Meta-analysis | PMID: 7389356'
  },
  E2E: {
    name: 'Estradiol Enanthate IM',
    therapeutic: [100, 400],
    unit: 'pg/mL',
    CL: 5,
    Vd: 2500,
    ka: 0.004,
    F: 0.92,
    halfLife: 240,
    doseUnit: 'mg',
    intervalUnit: 'h',
    defaultDose: 5,
    defaultInterval: 168,
    ref: 'TfS Meta-analysis'
  }
};
